#------------------------------------------------------------------
### Configurations for testing
#------------------------------------------------------------------
@token= ENTER-YOUR-BEARER-TOKEN
@subscription_id = ENTER-YOUR-SUB-ID
@resource_group = ENTER-YOUR-RESOURCE-GROUP
@account_name = ENTER-YOUR-ACCOUNT-NAME
@project_name = ENTER-YOUR-PROJECT-NAME

#configurations for connections
@connection_name = ENTER-YOUR-CONNECTION-NAME
@connection_target = ENTER-THE-URL-OF-YOUR-AOAI-RESOURCE for e.g.https://namikhai-myaoaiservices.openai.azure.com/
@connection_key = ENTER-API-KEY-FOR-YOUR-AOAI-RESOURCE

#Common variables - Dont change these variables for now
@location_name = eastus2euap
@api_version=2025-04-01-preview

#------------------------------------------------------------------
### Create Account
#------------------------------------------------------------------
PUT https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "Microsoft.CognitiveServices/accounts",
  "name": "{{account_name}}",
  "location": "{{location_name}}",
  "kind": "AIServices",
  "sku": {
    "name": "S0"
  },
  "identity": {
    "type": "SystemAssigned"
  },
  "properties": {
    "isAiFoundryType": true,
    "customSubDomainName": "{{account_name}}",
    "publicNetworkAccess": "Enabled",
    "networkAcls": {
      "defaultAction": "Allow",
      "virtualNetworkRules": [],
      "ipRules": []
    },
    "publicNetworkAccess": "Enabled",
    "disableLocalAuth": false,
    "allowProjectManagement": true
  }
}

#------------------------------------------------------------------
### List Accounts
#------------------------------------------------------------------
GET https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------------------------------------------------------
### Get Account by Name
#------------------------------------------------------------------
GET https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------------------------------------------------------
### Create Project
#------------------------------------------------------------------
PUT https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "{{account_name}}/{{project_name}}",
  "location": "{{location_name}}",
  "kind": "AIServices",
  "type": "Microsoft.CognitiveServices/accounts/projects",
  "identity": {
    "type": "SystemAssigned"
  },
  "sku": {
    "name": "S0"
  },
  "properties": {
    "customSubDomainName": "{{project_name}}",
    "publicNetworkAccess": "Enabled",
    "networkAcls": {
      "defaultAction": "Allow",
      "virtualNetworkRules": [],
      "ipRules": []
    }
  }
}

#------------------------------------------------------------------
### List Projects
#------------------------------------------------------------------
GET https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------------------------------------------------------
### Get Project
#------------------------------------------------------------------
GET https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------------------------------------------------------
### Create Connection
#------------------------------------------------------------------
PUT https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/connections/{{connection_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "properties": {
    "authType": "ApiKey",
    "category": "AzureOpenAI",
    "target": "https://oai-legacy-resource.openai.azure.com/",
    "credentials": {
      "key": "c50edc78ef9d4ebb9700f09379557fff"
    },
    "isSharedToAll": true,
    "metadata": {
      "ApiType": "Azure",
      "Location": "{{location_name}}",
      "ResourceId": "/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}"
    }
  }
}

#------------------------------------------------------------------
### List Connections
#------------------------------------------------------------------
GET https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/connections?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------------------------------------------------------
### Get a Connection
#------------------------------------------------------------------
GET https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/projects/{{project_name}}/connections/{{connection_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------------------------------------------------------
### Create Deployment - uncomment the block which you want to deploy
#------------------------------------------------------------------
# gpt-4o
# @publisher = OpenAI
# @deployment_name = gpt-4o
# @model_version=2024-11-20
#----------------------------
# Phi 4
@publisher = Microsoft
@deployment_name = Phi-4
@model_version=7
#-----------------------------
# Phi 3.5-mini-instruct
# @publisher = Microsoft
# @deployment_name = Phi-3.5-mini-instruct
# @model_version=6
#-----------------------------
#Cohere
# @publisher = Cohere
# @deployment_name = Cohere-command-r-08-2024
# @model_version=1
#-----------------------------
#Deepseek-V3
# @publisher = DeepSeek
# @deployment_name = DeepSeek-V3
# @model_version=1
#-----------------------------
PUT https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/deployments/{{deployment_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sku": {
    "name": "GlobalStandard",
    "capacity": 1
  },
  "properties": {
    "model": {
      "format": "{{publisher}}",
      "name": "{{deployment_name}}",
      "version": "{{model_version}}"
    }
  }
}

#------------------------------------------------------------------
### List Deployments
#------------------------------------------------------------------
GET https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/deployments?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json

#------------------------------------------------------------------
### Get a Deployment
#------------------------------------------------------------------
GET https://{{location_name}}.management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource_group}}/providers/Microsoft.CognitiveServices/accounts/{{account_name}}/deployments/{{deployment_name}}?api-version={{api_version}}
Authorization: Bearer {{token}}
Content-Type: application/json