#------------------------------------------------------------------

# Account details
@account_name = ENTER-YOUR-ACCOUNT-NAME-HERE
@project_name = ENTER-YOUR-PROJECT-NAME-HERE
@api_key = ENTER-YOUR-API-KEY-HERE

# Common Configs - dont change these variables for now
@api_version = latest
@api_version = 2025-05-01

# Model Deployments - Change these based on your deployment names
@deployment_name = Phi-4
# @deployment_name = gpt-4o
# @deployment_name = DeepSeek-V3

# Connections
@connection_name = ENTER-YOUR-CONNECTION-NAME-HERE

#------------------------------------------------------------------

#------------------------------------------------------------------
### List Deployments
#------------------------------------------------------------------
GET https://{{account_name}}.services.ai.azure.com/api/projects/{{project_name}}/deployments?api-version={{api_version}}
Authorization: Bearer {{api_key}}

#------------------------------------------------------------------
### Get Deployment By Name
#------------------------------------------------------------------
GET https://{{account_name}}.services.ai.azure.com/api/projects/{{project_name}}/deployments/{{deployment_name}}?api-version={{api_version}}
Authorization: Bearer {{api_key}}

#------------------------------------------------------------------
### List Connections
#------------------------------------------------------------------
GET https://{{account_name}}.services.ai.azure.com/api/projects/{{project_name}}/connections?api-version={{api_version}}
Authorization: Bearer {{api_key}}

#------------------------------------------------------------------
### Get a Connection
#------------------------------------------------------------------
GET https://{{account_name}}.services.ai.azure.com/api/projects/{{project_name}}/connections/{{connection_name}}?api-version={{api_version}}
Authorization: Bearer {{api_key}}

#------------------------------------------------------------------
### List Datasets
#------------------------------------------------------------------
GET https://{{account_name}}.services.ai.azure.com/api/projects/{{project_name}}/datasets?api-version={{api_version}}
Authorization: Bearer {{api_key}}

#------------------------------------------------------------------
### Get Dataset By Name
#------------------------------------------------------------------
@dataset_name = ENTER-YOUR-DATASET-NAME-HERE
GET https://{{account_name}}.services.ai.azure.com/api/projects/{{project_name}}/datasets/{{dataset_name}}?api-version={{api_version}}
Authorization: Bearer {{api_key}}

#------------------------------------------------------------------
### List Indexes
#------------------------------------------------------------------
GET https://{{account_name}}.services.ai.azure.com/api/projects/{{project_name}}/indexes?api-version={{api_version}}
Authorization: Bearer {{api_key}}

#------------------------------------------------------------------
### GET Index By Name
#------------------------------------------------------------------
@index_name = ENTER-YOUR-INDEX-NAME-HERE
GET https://{{account_name}}.services.ai.azure.com/api/projects/{{project_name}}/indexes/{{index_name}}?api-version={{api_version}}
Authorization: Bearer {{api_key}}